version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-node-browsers
    
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      
    steps:
    - checkout
    - run: sudo apt update
    - run: apt list --upgradable
    - run: google-chrome --version
    - run: chmod +777 chromedriver
    - run: chmod +777 src/chromedriver
    - run: chmod +777 test-output
    - run: xvfb-run java -Dwebdriver.chrome.driver=chromedriver -jar selenium-server-standalone-3.141.59.jar >/dev/null 2>&1 &
    - run: chromedriver --version
    - run: java -version
    - run: java -cp "testng-6.14.3.jar:jcommander-1.7.jar:bin" org.testng.TestNG testng.xml
