version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers-legacy
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - setup_remote_docker: 
         docker_layer_caching: true
    - run: sudo apt update
    - run: chmod +777 chromedriver
    - run: chmod +777 src/chromedriver
    - run: chmod +777 test-output
    - run: java -cp "/home/circleci/repo/eclipse.jar:/home/circleci/repo/beanshell.bsh.b6.jar:snakeyaml.jar:/home/circleci/repo/selenium-server-standalone-3.141.59.jar:/home/circleci/repo/testng-6.14.3.jar:/home/circleci/repo/jcommander-1.7.jar:/home/circleci/repo/bin/" org.testng.TestNG testng.xml
    
    - store_test_results:
    path: test-output
