version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers-legacy
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - setup_remote_docker: 
         docker_layer_caching: true
    - run: sudo apt update
    - run: apt list --upgradable
    - run: pwd
    - run: google-chrome --version
    - run: chmod +777 chromedriver
    - run: chmod +777 src/chromedriver
    - run: chmod +777 test-output
    #- run: xvfb-run java -Dwebdriver.chrome.driver=chromedriver -jar selenium-server-standalone-3.141.59.jar >/dev/null 2>&1 &
    - run: chromedriver --version
    - run: java -version
    - run: java -cp eclipse.jar:beanshell.bsh.b6.jar:snakeyaml.jar:selenium-server-standalone-3.141.59.jar:testng-6.14.3.jar:jcommander-1.7.jar:bin/ org.testng.TestNG testng.xml
